name: Build Release Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller requests

      - name: Build executable
        run: |
          pyinstaller main.py --onefile --noconsole

      - name: Download Whisper model from Hugging Face
        run: |
          curl -L -o dist/ggml-large-v3-turbo-q8_0.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path dist\* -DestinationPath twims_release.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: twims_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}