name: Build Release Executable

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller requests

      - name: Build with build.py
        run: python build.py --clean --output="twims_${{ github.event.release.tag_name}}" --console --download-model --model-url="https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin"

      # - name: Build executable
      #   run: |
      #     pyinstaller main.py --onefile --name "twims_${{ github.event.release.tag_name }}"

      - name: Download Whisper model from Hugging Face
        run: |
          curl -L -o dist/ggml-large-v3-turbo-q8_0.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin

      - name: Set release zip name
        run: |
          echo "ZIP_NAME=twims_${{ github.event.release.tag_name }}.zip" >> $env:GITHUB_ENV
      
      - name: Debug ZIP name
        shell: pwsh
        run: echo "ZIP will be named $env:ZIP_NAME"
      
      - name: Create ZIP archive
        shell: pwsh
        run: |
          echo "Creating archive: $env:ZIP_NAME"
          Compress-Archive -Path "dist\*" -DestinationPath "$env:ZIP_NAME"
      
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ZIP_NAME }}
            dist/twims_${{ github.event.release.tag_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}