name: Build Release Executable

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller requests

      - name: Build executable
        run: |
          pyinstaller main.py --onefile --noconsole

      - name: Download Whisper model from Hugging Face
        run: |
          curl -L -o dist/ggml-large-v3-turbo-q8_0.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin

      - name: Set release zip name
        id: zipname
        run: echo "ZIP_NAME=twims_${{ github.event.release.tag_name }}.zip" >> $GITHUB_ENV
        
      - name: Create ZIP archive
        run: |
          Compress-Archive -Path dist\* -DestinationPath ${{ env.ZIP_NAME }}
        
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}